services:
  - type: web
    name: church-portal
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn church_portal.wsgi:application"
    plan: starter
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: false

  - type: pserv
    name: church-portal-db
    env: postgresql
    plan: starter
    ipAllowList: []
