# Generated by Django 5.0.3 on 2025-08-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Mwanaume"),
                            ("Female", "Mwanamke"),
                            ("Prefer not to say", "Sipendi kusema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Bila ndoa"),
                            ("Married", "Kwenye ndoa"),
                            ("Divorced", "Talaka"),
                            ("Widowed", "Mjane"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("salvation_date", models.DateField(blank=True, null=True)),
                (
                    "baptized",
                    models.CharField(
                        choices=[("Yes", "Ndio"), ("No", "Hapana")], max_length=5
                    ),
                ),
                ("baptism_date", models.DateField(blank=True, null=True)),
                (
                    "membership_class",
                    models.CharField(
                        choices=[
                            ("Yes", "Ndio"),
                            ("No", "Hapana"),
                            ("Not Yet", "Bado"),
                        ],
                        max_length=10,
                    ),
                ),
                ("previous_church", models.CharField(blank=True, max_length=100)),
                ("emergency_name", models.CharField(max_length=100)),
                ("emergency_relation", models.CharField(max_length=50)),
                ("emergency_phone", models.CharField(max_length=15)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("New", "Mshirika Mpya"),
                            ("Transfer", "Aliyehamia"),
                            ("Returning", "Anayerudi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("registration_date", models.DateField()),
            ],
        ),
    ]
