# Generated by Django 5.0.3 on 2025-08-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="age_category",
            field=models.CharField(
                choices=[
                    ("Mtoto", "Mtoto"),
                    ("Kijana", "Kijana"),
                    ("Mtu mzima", "Mtu mzima"),
                ],
                default="Mtu mzima",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_id",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "Bila ndoa"),
                    ("Married", "Kwenye ndoa"),
                    ("Divorced", "Talaka"),
                    ("Widowed", "Mjane"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="membership_class",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Ndio"), ("No", "Hapana"), ("Not Yet", "Bado")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
