# Generated by Django 5.0.3 on 2025-08-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_member_age_category_member_membership_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-registration_date', 'full_name'], 'verbose_name': 'Mshirika', 'verbose_name_plural': 'Washirika'},
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_id'], name='membership__members_4a9762_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['full_name'], name='membership__full_na_99e641_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['registration_date'], name='membership__registr_ee8afd_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_type'], name='membership__members_cf75e9_idx'),
        ),
    ]
