# Generated by Django 4.2.23 on 2025-08-22 16:51

from django.db import migrations, models
import django.db.models.deletion
import sys
import os

# Add the project root to the path to import safe_migration_utils
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from safe_migration_utils import SafeAddField, SafeAlterField


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0004_branch_newscategory_attendancesession_member_branch_and_more",
        ),
        ("authentication", "0001_initial"),
    ]

    operations = [
        SafeAddField(
            model_name="userprofile",
            name="branches",
            field=models.ManyToManyField(
                blank=True,
                help_text="Branches this user has access to",
                related_name="users",
                to="membership.branch",
            ),
        ),
        SafeAddField(
            model_name="userprofile",
            name="primary_branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary branch for this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_users",
                to="membership.branch",
            ),
        ),
        SafeAlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("secretary", "Secretary/Clerk"),
                    ("pastor", "Pastor/Leader"),
                    ("branch_admin", "Branch Administrator"),
                    ("admin", "System Administrator"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
